[package]
name = "csv_plotters"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.44.1", features = ["csv"] }
plotters = "0.3.7"

[dependencies.plotters-canvas]
version = "0.3.0"
